remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Faruk Başer]
description: [Rust-Lang Developer | Cybersecurity | Linux]

sass:
    style: compressed

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    entity_output: as_char

include: ['_pages']
